// Generated by CoffeeScript 1.7.1
(function() {
  var Graph, Simulation, Spring, makeCounter, rk4;

  $(function() {
    var simulation;
    simulation = new Simulation;
    $("#start").click(function() {
      return simulation.startSimulation();
    });
    return $("#stop").click(function() {
      return simulation.stopSimulation();
    });
  });

  Simulation = (function() {
    function Simulation() {
      this.isRunning = false;
      this.counter = makeCounter(0.5);
      this.spring = new Spring;
      this.spring.reset(1, 0);
      this.graphs = [];
      this.graphs.push(new Graph("graph1", 800, 200, 0.5));
      this.graphs.push(new Graph("graph2", 800, 200, 0.5));
    }

    Simulation.prototype.startSimulation = function() {
      var that;
      console.log("Simulation started");
      that = this;
      if (!this.isRunning) {
        this.process = setInterval((function() {
          return that.simulate();
        }), 100);
      }
      return this.isRunning = true;
    };

    Simulation.prototype.stopSimulation = function() {
      clearInterval(this.process);
      this.isRunning = false;
      return console.log("Simulation ended");
    };

    Simulation.prototype.resetSimulation = function() {};

    Simulation.prototype.simulate = function() {
      var graph, t, v, x, _i, _len, _ref, _ref1, _results;
      t = this.counter();
      _ref = this.spring.next(0.5), x = _ref[0], v = _ref[1];
      this.graphs[0].data.push(x);
      this.graphs[1].data.push(v);
      _ref1 = this.graphs;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        graph = _ref1[_i];
        graph.path.attr("d", graph.lineGenerator(graph.data)).attr("transform", null).transition().duration(50).ease("linear").attr("transform", "translate(" + graph.xScale(-1) + ",0)");
        _results.push(graph.data.shift());
      }
      return _results;
    };

    return Simulation;

  })();

  Graph = (function() {
    function Graph(graphID, width, height, delta) {
      var margin, n, svg;
      n = 100;
      this.data = [];
      while (this.data.length < n) {
        this.data.push(0);
      }
      margin = {
        top: 20,
        right: 20,
        bottom: 20,
        left: 100
      };
      svg = d3.select("#" + graphID).append("svg").attr("width", width + margin.left + margin.right).attr("height", height + margin.top + margin.bottom).append("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");
      svg.append("defs").append("clipPath").attr("id", "clip").append("rect").attr("width", width).attr("height", height);
      svg.append("rect").attr("width", width).attr("height", height).attr("fill", "none").attr("stroke", "black").attr("stroke-width", 0.5);
      this.xScale = d3.scale.linear().domain([0, n - 1]).range([0, width]);
      this.yScale = d3.scale.linear().domain([-2, 2]).range([height, 0]);
      svg.append("g").attr("class", "x axis").attr("transform", "translate(0," + this.yScale(0) + ")").call(d3.svg.axis().scale(this.xScale).orient("bottom").ticks(0));
      svg.append("g").attr("class", "y axis").call(d3.svg.axis().scale(this.yScale).orient("left"));
      this.lineGenerator = d3.svg.line().x(function(d, i) {
        return this.xScale(i);
      }).y(function(d, i) {
        return this.yScale(d);
      }).interpolate("basis");
      this.path = svg.append("g").attr("clip-path", "url(#clip)").append("path").attr("d", this.lineGenerator(this.data)).attr("stroke", "blue").attr("stroke-width", 2).attr("fill", "none");
    }

    return Graph;

  })();

  Spring = (function() {
    function Spring(mass, elasticity, damping, externalForce) {
      this.mass = mass != null ? mass : 1.0;
      this.elasticity = elasticity != null ? elasticity : 1.0;
      this.damping = damping != null ? damping : 0.0;
      this.externalForce = externalForce != null ? externalForce : (function(t) {
        return 0.0;
      });
    }

    Spring.prototype.reset = function(x0, v0) {
      this.t = 0.0;
      this.x = x0;
      return this.v = v0;
    };

    Spring.prototype.next = function(delta) {
      var c, f, f1, f2, k, m, _ref;
      m = this.mass;
      k = this.elasticity;
      c = this.damping;
      f = this.externalForce;
      f1 = function(t, ys) {
        return ys[1];
      };
      f2 = function(t, ys) {
        return (f(t) - c * ys[1] - k * ys[0]) / m;
      };
      _ref = rk4([f1, f2], delta, this.t, [this.x, this.v]), this.x = _ref[0], this.v = _ref[1];
      this.t += delta;
      return [this.x, this.v];
    };

    return Spring;

  })();

  makeCounter = function(delta) {
    var t;
    t = 0;
    return function() {
      var r;
      r = t;
      t += delta;
      return r;
    };
  };

  rk4 = function(fs, h, t, ys) {
    var h2, k1, k2, k3, k4, scalarMul, u, v, vectorSum, w;
    vectorSum = function(v1, v2) {
      var i, res, v, _i, _len;
      res = [];
      for (i = _i = 0, _len = v1.length; _i < _len; i = ++_i) {
        v = v1[i];
        res.push(v1[i] + v2[i]);
      }
      return res;
    };
    scalarMul = function(v, a) {
      return v.map(function(x) {
        return x * a;
      });
    };
    h2 = 0.5 * h;
    k1 = fs.map(function(f) {
      return f(t, ys);
    });
    k2 = fs.map(function(f) {
      return f(t + h2, vectorSum(ys, scalarMul(k1, h2)));
    });
    k3 = fs.map(function(f) {
      return f(t + h2, vectorSum(ys, scalarMul(k2, h2)));
    });
    k4 = fs.map(function(f) {
      return f(t + h, vectorSum(ys, scalarMul(k3, h)));
    });
    u = scalarMul(k2, 2);
    v = scalarMul(k3, 2);
    w = vectorSum(vectorSum(vectorSum(k1, u), v), k4);
    return vectorSum(ys, scalarMul(w, (1 / 6.0) * h));
  };

}).call(this);
